version: 2.1

executors:
  default:
    docker:
      - image: cimg/ruby:2.7-node

jobs:
  build:
    executor: default
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler -v 2.1.4

      # Restore bundle cache
      - restore_cache:
          keys:
          - dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run:
          name: Install dependencies
          command: bundle install
      
      # Save bundle cache
      - restore_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle      
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/postgres:9.5-alpine
        environment:
          # POSTGRES_USER: test_user
          POSTGRES_DB: roster-bots_test
          # POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: test_user
      PGPASSWORD: ""
      RAILS_ENV: test
    
    steps:
      - run:
          name: Run tests
          command: bundle exec rspec
    

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
