version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers

jobs:
  build:
    executor: default

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler -v 2.1.4

      # Restore bundle cache
      - restore_cache:
          keys:
          - dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run:
          name: Install dependencies
          command: bundle install
      
      # Save bundle cache
      - restore_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      

      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
